import { BackgroundGenerator } from "./BackgroundGenerator.js";
import { BackgroundRenderer } from "./BackgroundRenderer.js";
import { BulletBill } from "./BulletBill.js";
import { Character } from "./Character.js";
import { CoinAnim } from "./CoinAnim.js";
import { Enemy } from "./Enemy.js";
import { Fireball } from "./Fireball.js";
import { FireFlower } from "./FireFlower.js";
import { FlowerEnemy } from "./FlowerEnemy.js";
import { ImprovedNoise } from "./ImprovedNoise.js";
import { Level } from "./Level.js";
import { LevelGenerator } from "./LevelGenerator.js";
import { LevelRenderer } from "./LevelRenderer.js";
import { LevelState } from "./LevelState.js";
import { LT } from "./LevelType.js";
import { LoadingState } from "./LoadingState.js";
import { LoseState } from "./LoseState.js";
import { MapState } from "./MapState.js";
import { MT } from "./MapTile.js";
import { Mushroom } from "./Mushroom.js";
import { NotchSprite } from "./NotchSprite.js";
import { ODDS } from "./Odds.js";
import { Particle } from "./Particle.js";
import { Shell } from "./Shell.js";
import { Sparkle } from "./Sparkle.js";
import { SC } from "./SpriteCuts.js";
import { SpriteTemplate } from "./SpriteTemplate.js";
import { TILE } from "./Tile.js";
import { TitleState } from "./TitleState.js";
import { WinState } from "./WinState.js";
interface MARIO {
    SpriteCuts: SC;
    Tile: TILE;
    LevelType: LT;
    Odds: ODDS;
    MapTile: MT;
    Level: typeof Level;
    BackgroundGenerator: typeof BackgroundGenerator;
    BackgroundRenderer: typeof BackgroundRenderer;
    ImprovedNoise: typeof ImprovedNoise;
    NotchSprite: typeof NotchSprite;
    Character: typeof Character;
    LevelRenderer: typeof LevelRenderer;
    LevelGenerator: typeof LevelGenerator;
    SpriteTemplate: typeof SpriteTemplate;
    Enemy: typeof Enemy;
    Fireball: typeof Fireball;
    Sparkle: typeof Sparkle;
    CoinAnim: typeof CoinAnim;
    Mushroom: typeof Mushroom;
    Particle: typeof Particle;
    FireFlower: typeof FireFlower;
    BulletBill: typeof BulletBill;
    FlowerEnemy: typeof FlowerEnemy;
    Shell: typeof Shell;
    TitleState: typeof TitleState;
    LoadingState: typeof LoadingState;
    LoseState: typeof LoseState;
    WinState: typeof WinState;
    MapState: typeof MapState;
    LevelState: typeof LevelState;
    GlobalMapState: MapState;
    MarioCharacter: Character;
}
declare const Mario: MARIO;
export default Mario;
